development:
  AUTH_TOKEN: "OKbwY5J/iAW2V5g2k/TP84FJvWl5QsFHlagfwooX5sl4NhBGvpMV6VNIkPWpYcuqpWj5AC4SDdyrdrIx7vsR7A=="
  DB_USER: "barter"
  DB_PASS: "kol4po"
production:
  AUTH_TOKEN: "OKbwY5J/iAW2V5g2k/TP84FJvWl5QsFHlagfwooX5sl4NhBGvpMV6VNIkPWpYcuqpWj5AC4SDdyrdrIx7vsR7A=="
  DB_USER: "barter"
  DB_PASS: "kol4po"  